spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              route-id-prefix: ${spring.application.name}
          routes:
            - id: iam-service
              uri: lb://iam-service
              predicates:
                - Path=/api/v1/authentication/**
            - id: tasks-service
              uri: lb://tasks-service
              predicates:
                - Path=/api/v1/tasks/**
            - id: room-service
              uri: lb://room-service
              predicates:
                - Path=/api/v1/room/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/inventory/**
            - id: employees-service
              uri: lb://employees-service
              predicates:
                - Path=/api/v1/employees/**
            - id: notifications-service
              uri: lb://notifications-service
              predicates:
                - Path=/ws/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
    urls:
#      - name: Keycloak Service
#        url: /api/v1/auth/docs
  #      - name: User Service
  #        url: /user-service/v3/api-docs
  api-docs:
    enabled: true

info:
  application:
    name: Api Gateway
    description: InnControl API Gateway
    version: 1.0.0
  maintainer: "contact@incontroll.pe"
  java-version: ${java.version}
  java-vendor: ${java.vendor}

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    com.github.inncontrol: DEBUG